name: flutter_contacts
description: Flutter plugin to read, create, update, delete and observe native contacts on Android and iOS, with vCard support
version: 0.3.0
homepage: https://github.com/QuisApp/flutter_contacts

environment:
  sdk: '>=2.12.0-259.16.beta <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider: ^2.0.1
  pedantic: ^1.10.0
  test: ^1.16.5

flutter:
  plugin:
    platforms:
      android:
        package: co.quis.flutter_contacts
        pluginClass: FlutterContactsPlugin
      ios:
        pluginClass: FlutterContactsPlugin
