name: flutter_contacts
description: Flutter plugin to read, create, update, delete and observe native contacts on Android and iOS, with group support, vCard support, and contact permission handling
version: 1.1.8
homepage: https://github.com/QuisApp/flutter_contacts

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.16.5

flutter:
  plugin:
    platforms:
      android:
        package: co.quis.flutter_contacts
        pluginClass: FlutterContactsPlugin
      ios:
        pluginClass: FlutterContactsPlugin
